
easy_admin:
    site_name: 'Evaluation Administration'
#    design:
#      menu:
#        - Evaluation
#        - Content
#        - { entity: 'QuestionGroup', label: 'Questions' }
#        - { entity: 'Evaluation', label: 'Evaluation' }
#        - { entity: 'Evaluation', label: 'Evaluation' }
    entities:
      Evaluation:
        class: AppBundle\Entity\Evaluation
        label: 'Evaluations'
        list:
          title: 'Evaluations'
        form:
          fields:
            - name
            - type
            - { property: 'contents', type_options: { by_reference: false} }
            - { property: 'questions', type_options: { by_reference: false} }
            - { property: 'metrics', type_options: { by_reference: false} }
            - { property: 'users', type_options: { by_reference: false} }
      Content:
        label: 'Contents'
        list:
          title: 'Contents'
        class: AppBundle\Entity\Content
      Question:
        class: AppBundle\Entity\Question\Question
        label: 'Questions'
        list:
          title: 'Questions'
          fields:
            - id
            - name
            - type
            - answers
#            - { property: appearance, type_options: {choices_as_values: true } }
            - appearance
            - ordinance
        form:
          fields:
            - name
            - type
            - answers
            - { property: appearance, type: choice, type_options: { choices: [pre: pre, post: post], choices_as_values: true } }
            - ordinance
      Answer:
        class: AppBundle\Entity\Question\Answer
        label: 'Answers'
        list:
          title: 'Answers'
          fields:
            - id
            - name
            - text
            - question
            - ordinance
            - evaluation
#      QuestionType:
#        class: AppBundle\Entity\Question\QuestionType
#        list:
#          fields:
#            - { property: type, type_options: {choices_as_values: true } }
#        form:
#          fields:
#            - { property: type, type: choice, type_options: { choices: [radioBox: radioBox, checkBox: checkBox, selectionBox: selectionBox, text: text, textArea: textArea, slider: slider], choices_as_values: true } }
      User:
        class: AppBundle\Entity\User
        label: 'Users'
        list:
          title: 'Users'
          fields:
            - id
            - username
            - email
            - evaluation
            - enabled
        form:
          fields:
            - username
            - password
            - email
            - roles
            - enabled
            - evaluation
#      Metrics:
#        class: AppBundle\Entity\Metrics

